name: pharmacy_store
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.4.0'

dependencies:
  flutter:
    sdk: flutter

  # واجهات وأيقونات
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0

  # الوظائف الأساسية
  http: ^1.1.0
  provider: ^6.1.5
  shared_preferences: ^2.2.1
  intl: ^0.20.2
  fluttertoast: ^8.2.12
  logger: ^2.0.2
  share_plus: ^7.2.1       # ✅ تم نقلها هنا
  url_launcher: ^6.2.5     # ✅ تم نقلها هنا

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
